#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket server..."
        /usr/bin/aesdsocket -d
        ;;
    stop)
        echo "Stopping aesdsocket server..."
        pkill aesdsocket
        ;;
    *)
        echo $"Usage: $0 {start|stop}"
        exit 1
esac

exit $?
